version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mariadb
      DB_NAME_2: rksd
      DB_USER: rksd
      DB_PASSWORD: nJkyj2pOsfUi
    volumes:
      - ./web:/var/www/html
    ports:
      - "13080:80"
    working_dir: /var/www/html
    command: php -S 0.0.0.0:80 -t /var/www/html

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: hW3e4iNuFDqs
      MYSQL_DATABASE: rksd
      MYSQL_USER: rksd
      MYSQL_PASSWORD: nJkyj2pOsfUi
    volumes:
      # SQL files present in this directory will initialise the DB if it is empty on container start
      - ./sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - acdh-stud-db:/var/lib/mysql
    ports:
      - "13006:3306"
volumes:
  acdh-stud-db:
    external: true
    name: acdh-stud-db
