<?php declare(strict_types=1);
namespace rekdagyothub;

use PDO;
use RuntimeException;

/**
 * Generates an SQL file from all those statements that manipulate date while still returning rows for non-manipulation
 * SELECT and SHOW statements.
 */
class ImmutablePdo extends PDO
{
    private $sqlFile;

    public function __construct($dsn, $username, $passwd, $sqlFile)
    {
        parent::__construct(
            $dsn,
            $username,
            $passwd,
            [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ,
            ]
        );
        $this->exec('SET NAMES utf8');
        $this->sqlFile = $sqlFile;
    }

    public function prepare($statement, array $driver_options = [])
    {
        parent::prepare($statement, $driver_options); // TODO: Change the autogenerated stub
    }

    public function beginTransaction()
    {
        throw new RuntimeException('Transactions are not supported by this instance');
    }

    public function commit()
    {
        throw new RuntimeException('Transactions are not supported by this instance');
    }

    public function rollBack()
    {
        throw new RuntimeException('Transactions are not supported by this instance');
    }

    public function inTransaction()
    {
        return false;
    }

    public function exec($statement)
    {
        parent::exec($statement); // TODO: Change the autogenerated stub
    }

    public function query($statement, $mode = PDO::ATTR_DEFAULT_FETCH_MODE, $arg3 = null, array $ctorargs = [])
    {
        parent::query($statement, $mode, $arg3, $ctorargs); // TODO: Change the autogenerated stub
    }
}
