alter table student_birth_date_value add is_doubtful set ('true') default '' not null;
alter table student_birth_place_value add is_doubtful set ('true') default '' not null;
alter table student_father_value add is_doubtful set ('true') default '' not null;
alter table student_gender_value add is_doubtful set ('true') default '' not null;
alter table student_given_names_value add is_doubtful set ('true') default '' not null;
alter table student_guardian_value add is_doubtful set ('true') default '' not null;
alter table student_last_name_value add is_doubtful set ('true') default '' not null;
alter table student_last_school_value add is_doubtful set ('true') default '' not null;
alter table student_remarks_value add is_doubtful set ('true') default '' not null;
